// <auto-generated />
using KitapApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KitapApi.Data.Migrations
{
    [DbContext(typeof(KitaplarDbContext))]
    partial class KitaplarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KitapApi.Data.Kitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yazar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Kitaplar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Çalıkuşu",
                            Yazar = "Reşat Nuri Güntekin",
                            Yil = 1922
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Çulsuzlar",
                            Yazar = "Dan Kavanagh",
                            Yil = 2002
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Kendi Everest'inize Tırmanın",
                            Yazar = "Nasuh Mahruki",
                            Yil = 2019
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Körlük",
                            Yazar = "Jose Saramago",
                            Yil = 1995
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Aptallığın övgüsü",
                            Yazar = "Erasmus",
                            Yil = 1511
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
